import {
    MESSAGE_SENT_SUCCESS, MESSAGE_SENT_FAIL, MESSAGE_REQUEST_SUCCESS,
    MESSAGE_REQUEST_FAIL, LOAD_MESSAGES_SUCCESS, LOAD_MESSAGES_FAIL,
    LOAD_MESSAGE_SUCCESS, LOAD_MESSAGE_FAIL
} from '../types'


