// Auth Dispatch States
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOAD_CURRENT_SUCCESS = 'LOAD_CURRENT_SUCCESS'
export const LOAD_CURRENT_FAIL = 'LOAD_CURRENT_FAIL'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'

// ALERT DISPATCH STATES
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// POST DISPATCH STATES
export const UPLOAD_POST_SUCCESS = 'UPLOAD_POST_SUCCESS'
export const UPLOAD_POST_FAIL = 'UPLOAD_POST_FAIL'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAIL = 'LOAD_POST_FAIL'
export const DESTROY_POST_SUCCESS = 'DESTROY_POST_SUCCESS'
export const DESTORY_POST_FAIL = 'DESTORY_POST_FAIL'
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS'
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS'
export const DISLIKE_POST_FAIL = 'DISLIKE_POST_FAIL'

// COMMENT DISPATCH STATES
export const UPLOAD_COMMENT_SUCCESS = 'UPLOAD_COMMENT_SUCCESS'
export const UPLOAD_COMMENT_FAIL = 'UPLOAD_COMMENT_FAIL'
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'
export const LOAD_COMMENTS_FAIL = 'LOAD_COMMENTS_FAIL'
export const LOAD_COMMENT_SUCCESS = 'LOAD_COMMENT_SUCCESS'
export const LOAD_COMMENT_FAIL = 'LOAD_COMMENT_FAIL'
export const DESTROY_COMMENT_SUCCESS = 'DESTROY_COMMENT_SUCCESS'
export const DESTORY_COMMENT_FAIL = 'DESTORY_COMMENT_FAIL'
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS'
export const COMMENT_UPDATE_FAIL = 'COMMENT_UPDATE_FAIL'
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'
export const LIKE_COMMENT_FAIL = 'LIKE_COMMENT_FAIL'
export const DISLIKE_COMMENT_SUCCESS = 'DISLIKE_COMMENT_SUCCESS'
export const DISLIKE_COMMENT_FAIL = 'DISLIKE_COMMENT_FAIL'

// USERPROFILE DISPATCH STATES
export const LOAD_USERPROFILES_SUCCESS = 'LOAD_USERPROFILES_SUCCESS'
export const LOAD_USERPROFILES_FAIL = 'LOAD_USERPROFILES_FAIL'
export const LOAD_USERPROFILE_SUCCESS = 'LOAD_USERPROFILE_SUCCESS'
export const LOAD_USERPROFILE_FAIL = 'LOAD_USERPROFILE_FAIL'
export const USERPROFILE_UPDATE_SUCCESS = 'USERPROFILE_UPDATE_SUCCESS'
export const USERPROFILE_UPDATE_FAIL = 'USERPROFILE_UPDATE_FAIL'
export const FOLLOW_USERPROFILE_SUCCESS = 'FOLLOW_USERPROFILE_SUCCESS'
export const FOLLOW_USERPROFILE_FAIL = 'FOLLOW_USERPROFILE_FAIL'
export const UNFOLLOW_USERPROFILE_SUCCESS = 'UNFOLLOW_USERPROFILE_SUCCESS'
export const UNFOLLOW_USERPROFILE_FAIL = 'UNFOLLOW_USERPROFILE_FAIL'
export const LOAD_USER_FOLLOWERS_SUCCESS = 'LOAD_USER_FOLLOWERS_SUCCESS'
export const LOAD_USER_FOLLOWERS_FAIL = 'LOAD_USER_FOLLOWERS_FAIL'
export const LOAD_ALL_FOLLOWERS_SUCCESS = 'LOAD_ALL_FOLLOWERS_SUCCESS'
export const LOAD_ALL_FOLLOWERS_FAIL = 'LOAD_ALL_FOLLOWERS_FAIL'




export const LOAD_USERINFO_SUCCESS = 'LOAD_USERINFO_SUCCESS'
export const LOAD_USERINFO_FAIL = 'LOAD_USERINFO_FAIL'

// Thread Dispatch States
export const CREATE_THREAD_SUCCESS = 'CREATE_THREAD_SUCCESS'
export const CREATE_THREAD_FAIL = 'CREATE_THREAD_FAIL'
export const DELETE_THREAD_SUCCESS = 'DELETE_THREAD_SUCCESS'
export const DELETE_THREAD_FAIL = 'DELETE_THREAD_FAIL'
export const UPDATE_THREAD_SUCCESS = 'UPDATE_THREAD_SUCCESS'
export const UPDATE_THREAD_FAIL = 'UPDATE_THREAD_FAIL'
export const LOAD_THREADS_SUCCESS = 'LOAD_THREADS_SUCCESS'
export const LOAD_THREADS_FAIL = 'LOAD_THREADS_FAIL'
export const LOAD_THREAD_SUCCESS = 'LOAD_THREAD_SUCCESS'
export const LOAD_THREAD_FAIL = 'LOAD_THREAD_FAIL'

