# Generated by Django 4.1.4 on 2022-12-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
