# Generated by Django 4.1.4 on 2022-12-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
